### ISSUE TITLE
onvif cannot connect to homey

### ISSUE THREAD

**Issue by tha-jr** [AdyRock/com.onvif#19]
hi, been trying to connect the Imou LOOC but been getting an error message, Error: Network request failed, what can be the issue?

**Comment by tha-jr** [comment]
![58A6C416-5928-4869-9407-96EDD331C25C_4_5005_c](https://user-images.githubusercontent.com/80521826/116367168-589f3b80-a807-11eb-9f15-56eaf850c4d2.jpeg)

**Comment by tha-jr** [comment]
[
<img width="473" alt="Screenshot 2021-04-28 at 09 55 47" src="https://user-images.githubusercontent.com/80521826/116367856-0a3e6c80-a808-11eb-94ec-fb0c2c64b0dc.png">
](url)

**Comment by AdyRock** [comment]
Is the camera on the same network as Homey?

Could you enable the log in the Configure app section, try to connect the camera and then send me the log using the send button.

**Comment by tha-jr** [comment]
yes the camera is on the same network

i sent the log to you

**Comment by AdyRock** [comment]
The camera is not returning a port number in the discovery information. Can you try manually setting it to port 80 or 8080 to see if either of those work?

**Comment by tha-jr** [comment]
tried the 80 one, finally worked. thanks
