### ISSUE TITLE
Tp Link Cameras

### ISSUE THREAD

**Issue by biordanescu** [AdyRock/com.onvif#2]
Hi Adrian,

I am trying to connect a Tp Link camera without success: the app finds the cameras with their specific IP's, I input the user and password, but get an error message regarding authorization.

The camera is a Tp Link NC450 with the latest firmware and below is the log:

* Reply from 192.168.31.66
* Reply from 192.168.31.66
* Reply from 192.168.31.66
* Reply from 192.168.31.66
* Reply from 192.168.31.14
* Reply from 192.168.31.14
* Reply from 192.168.31.14
* Reply from 192.168.31.14
* Discovered: [
  {
    "name": "192.168.31.66",
    "data": {
      "id": "192.168.31.66",
      "port": "2020"
    },
    "settings": {
      "username": "",
      "password": ""
    }
  },
  {
    "name": "192.168.31.14",
    "data": {
      "id": "192.168.31.14",
      "port": "2020"
    },
    "settings": {
      "username": "",
      "password": ""
    }
  }
]
* Testing connection credentials
* ----------------------------------------------------------------
* Connect to Camera 
* Connection Failed for 192.168.31.66 Port: 2020 Username: Admin
* Failed: {}

**Comment by AdyRock** [comment]
Looking at the log I am guessing it is an older version so could you try the latest test version to see if it works in that:
https://homey.app/en-gb/app/com.onvif/ONVIF-Camera/test/

**Comment by biordanescu** [comment]
Tried now, same result: ONVIF SOAP FAULT: Authority failure

**Comment by biordanescu** [comment]
App Started* 2020-04-25T19:38:44.738Z: Connection Failed for 192.168.31.66 Port: 2020 Username: Admin
* 2020-04-25T19:38:44.743Z: Failed: {}

**Comment by AdyRock** [comment]
There is another test version available with more error reporting so could you try that and sens me the log?
I have also ordered the camera so i can try it myself.

**Comment by biordanescu** [comment]
> you

Do you have a link to this another version? I cannot find it...

**Comment by AdyRock** [comment]
It's the same link as before. Each update overwrite the old one.

**Comment by biordanescu** [comment]
Found it, tried it. No luck...
Good thing you ordered a camera too. I sure hope you make it work. These are great cameras.

**Comment by biordanescu** [comment]
Maybe a different port than 2020?

**Comment by AdyRock** [comment]
Maybe. I have read a few reports online that say it's tricky to get working on ONVIF and to use a different port.
That would mean a is not performing to spec though as the image link is retrieved from the camera via a documented ONVIF call. So that would suggest it's reporting the wrong information.
Could you enable the logging option in the ONVIF app configuration, then restart the app and after about 30 seconds send me the log?
That might show me the response to the requests so I can check for errors. 
Looking like my camera will arrive next Saturday.

**Comment by biordanescu** [comment]
It only say "App started"

**Comment by biordanescu** [comment]
App Started* 2020-04-26T07:22:08.377Z: ====  Discovery Starting  ====
* 2020-04-26T07:22:08.715Z: Reply from {
  "protocol": "http:",
  "slashes": true,
  "auth": null,
  "host": "192.168.31.66:2020",
  "port": "2020",
  "hostname": "192.168.31.66",
  "hash": null,
  "search": null,
  "query": null,
  "pathname": "/onvif/device_service",
  "path": "/onvif/device_service",
  "href": "http://192.168.31.66:2020/onvif/device_service"
}
* 2020-04-26T07:22:09.708Z: Reply from {
  "protocol": "http:",
  "slashes": true,
  "auth": null,
  "host": "192.168.31.14:2020",
  "port": "2020",
  "hostname": "192.168.31.14",
  "hash": null,
  "search": null,
  "query": null,
  "pathname": "/onvif/device_service",
  "path": "/onvif/device_service",
  "href": "http://192.168.31.14:2020/onvif/device_service"
}
* 2020-04-26T07:22:13.441Z: ====  Discovery Finished  ====
* 2020-04-26T07:22:13.444Z: Discovered: [
  {
    "name": "192.168.31.66",
    "data": {
      "id": "192.168.31.66",
      "port": "2020"
    },
    "settings": {
      "username": "",
      "password": "",
      "ip": "192.168.31.66",
      "port": "2020"
    }
  },
  {
    "name": "192.168.31.14",
    "data": {
      "id": "192.168.31.14",
      "port": "2020"
    },
    "settings": {
      "username": "",
      "password": "",
      "ip": "192.168.31.14",
      "port": "2020"
    }
  }
]
* 2020-04-26T07:22:25.053Z: Testing connection credentials
* 2020-04-26T07:22:25.057Z: --------------------------
* 2020-04-26T07:22:25.064Z: Connect to Camera 192.168.31.66:2020 - Admin
* 2020-04-26T07:22:25.589Z: Connection Failed for 192.168.31.66 Port: 2020 Username: Admin
* 2020-04-26T07:22:25.596Z: Failed: {}

**Comment by AdyRock** [comment]
My camera arrived today so I eagerly set it up. There is good and bad news. I have managed to get the image capture working but it doesn't support ONVIF pullPoints, so no motion detection.
So a new test version (0.0.20) is available using the previous link that will show the manual 'NOW' image.
I will keep investigating to see if I can get motion detection to work and update you if I have any luck.

**Comment by biordanescu** [comment]
I still get the authority failure....

**Comment by biordanescu** [comment]
Log ID: 2020-04-29T16:19:07.702Z
App version 0.0.20

+1:0:0: ====  Discovery Starting  ====
+1:0:185: Reply from {
  "protocol": "http:",
  "slashes": true,
  "auth": null,
  "host": "192.168.31.14:2020",
  "port": "2020",
  "hostname": "192.168.31.14",
  "hash": null,
  "search": null,
  "query": null,
  "pathname": "/onvif/device_service",
  "path": "/onvif/device_service",
  "href": "http://192.168.31.14:2020/onvif/device_service"
}
+1:0:197: Reply from {
  "protocol": "http:",
  "slashes": true,
  "auth": null,
  "host": "192.168.31.220:8018",
  "port": "8018",
  "hostname": "192.168.31.220",
  "hash": null,
  "search": null,
  "query": null,
  "pathname": "/wsd",
  "path": "/wsd",
  "href": "http://192.168.31.220:8018/wsd"
}
+1:0:640: ====  Discovery Finished  ====
+1:0:6: Discovered: [
  {
    "name": "192.168.31.14",
    "data": {
      "id": "192.168.31.14",
      "port": "2020"
    },
    "settings": {
      "username": "",
      "password": "",
      "ip": "192.168.31.14",
      "port": "2020"
    }
  },
  {
    "name": "192.168.31.220",
    "data": {
      "id": "192.168.31.220",
      "port": "8018"
    },
    "settings": {
      "username": "",
      "password": "",
      "ip": "192.168.31.220",
      "port": "8018"
    }
  }
]
+1:0:797: Testing connection credentials
+1:0:2: --------------------------
+1:0:2: Connect to Camera 192.168.31.14:2020 - Admin
+1:0:156: Connection Failed for 192.168.31.14 Port: 2020 Username: Admin
+1:0:4: Failed: Error: ONVIF SOAP Fault: Authority failure
    at /lib/onvif/lib/utils.js:101:13
    at Parser.<anonymous> (/node_modules/xml2js/lib/parser.js:304:18)
    at Parser.emit (events.js:311:20)
    at SAXParser.onclosetag (/node_modules/xml2js/lib/parser.js:262:26)
    at emit (/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/node_modules/sax/lib/sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (/node_modules/xml2js/lib/parser.js:323:31)
    at Parser.parseString (/node_modules/xml2js/lib/parser.js:5:59)

**Comment by AdyRock** [comment]
Can you just check the user name. On mine it is admin not Admin and the error suggests an error like that.

**Comment by biordanescu** [comment]
Ok, it worked now. Stupid me. So how do I get the snapshot now?

**Comment by AdyRock** [comment]
Do you see an image in the device on Homey?

**Comment by biordanescu** [comment]
Nope. I only get this:
![Screenshot_20200429-210800](https://user-images.githubusercontent.com/61993229/80630923-a3a03a80-8a5d-11ea-8049-648b848b703c.jpg)

**Comment by biordanescu** [comment]
By the way - on your experience - what would be the best budget camera to use with Homey?

**Comment by AdyRock** [comment]
Can you try restarting the app to see if the image comes in then. 

I'm not sure what you call budget but of the cameras I have the best is the H.View but I have only test that, a Foscam and the TP NC 450. I have a HikVision camera on its way but that is more expensive. 

The H.View is the 4K IP POE bullet camera,  £80 on Amazon

**Comment by biordanescu** [comment]
Looks like a snapshot error:

Log ID: 2020-04-29T18:27:36.814Z
App version 0.0.20

+1:0:0: Initialising CameraDevice
+1:0:9: --------------------------
+1:0:8: Connect to Camera 192.168.31.66:2020 - admin
+1:0:17: Initialising CameraDevice
+1:0:3: --------------------------
+1:0:2: Connect to Camera 192.168.31.14:2020 - admin
+1:0:604: CONNECTED
+1:0:22: SnapShot error: TypeError: Cannot read property 'replace' of undefined
    at CameraDevice.setupImages (/drivers/camera/device.js:418:33)
    at CameraDevice.connectCamera (/drivers/camera/device.js:178:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
+1:0:253: CONNECTED
+1:0:12: SnapShot error: TypeError: Cannot read property 'replace' of undefined
    at CameraDevice.setupImages (/drivers/camera/device.js:418:33)
    at CameraDevice.connectCamera (/drivers/camera/device.js:178:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by AdyRock** [comment]
Sorry, I broke it by removing the user defined URL.

Version 0.0.21 is now available with the test link.

**Comment by biordanescu** [comment]
Great support!

**Comment by biordanescu** [comment]
Hi Adrian, one more question, not related to your app, but maybe you have some ideas:

Can I get homey to store the snapshots on my phone? Or whatever way to store them (cloud, local)?
