### ISSUE TITLE
Motion detection

### ISSUE THREAD

**Issue by perpatrik79** [AdyRock/com.onvif#20]
I cannot get motion-detection to work with my camera (see enclosed picture). 
Am I doing something wrong?

![B7EFC305-7DAE-4952-8D07-88AE30B599FE](https://user-images.githubusercontent.com/46899914/129598977-6f22d4c6-c712-402e-9c80-038184459cc1.png)

**Comment by AdyRock** [comment]
Could you try different motion notification to use methods.

**Comment by perpatrik79** [comment]
Hi!

I tried this and the only method that I am able to select is ”motionalarm”.
Ill try this and see if it works.

mån 16 aug. 2021 kl. 19:26 skrev Adrian Rockall ***@***.***>:

**Comment by AdyRock** [comment]
As it has been a while I hope your issue is resolved so I will close it now.
If you are still having problems then please get in touch again.
