### ISSUE TITLE
Imou Looc

### ISSUE THREAD

**Issue by jho80** [AdyRock/com.onvif#24]
Hello,

I have a Imou Looc camera that I want to use to trigger flows in Homey. Camera and motion detection works as it should with Imou app, but I can’t get it to trigger flows with Homey with the Homey Onvif camera app. Something with my settings? Also included the log info (following instruction that you made for another one here).

![4AF6CDBC-FB31-46E0-B9EC-4FC8349C48ED](https://user-images.githubusercontent.com/96890279/148035000-ace97684-a4cb-46d1-87d4-e141b8f8d0df.png)

![81CBDD8F-9B9D-477D-9033-AFF5CA2F151D](https://user-images.githubusercontent.com/96890279/148035048-5cc11d4b-8854-4651-b083-8b4322ad67c3.png)

Log ID: 2022-01-04T08:59:36.306Z
App version 1.1.32

9:59:36.306: Initialising CameraDevice (192.168.10.105)
9:59:36.320: --------------------------
9:59:36.329: Connect to Camera 192.168.10.105:80 - admin
9:59:36.352: getSystemDateAndTime (192.168.10.105): Started *****
9:59:36.372: 
_request (192.168.10.105): {
  "hostname": "192.168.10.105",
  "port": 80,
  "path": "/onvif/device_service",
  "agent": false,
  "timeout": 15000,
  "headers": {
    "Content-Type": "application/soap+xml",
    "Content-Length": 261,
    "charset": "utf-8"
  },
  "method": "POST"
}
Body: <s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope"><s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><GetSystemDateAndTime xmlns="http://www.onvif.org/ver10/device/wsdl"/></s:Body></s:Envelope>

9:59:37.546: Push renew every (192.168.10.105): 295000s  @ http://192.168.10.105/onvif/Subscription?Idx=3

9:59:37.630: Event data: (192.168.10.105) RuleEngine/CellMotionDetector/Motion: IsMotion = false
9:59:37.636: Event Trigger (192.168.10.105):IsMotion = false

9:59:37.691: Event data: (192.168.10.105) VideoSource/MotionAlarm: State = false

9:59:37.762: Event data: (192.168.10.105) VideoSource/GlobalSceneChange/AnalyticsService: State = false

9:59:37.783: Event data: (192.168.10.105) Device/Trigger/DigitalInput: LogicalState = false

9:59:37.805: Event data: (192.168.10.105) Monitoring/ProcessorUsage: Value = 0.47

9:59:37.827: Event data: (192.168.10.105) Monitoring/OperatingTime/LastReboot: Status = Sat Jan 01 2022 19:03:48 GMT+0100 (Central European Standard Time)

9:59:37.873: Event data: (192.168.10.105) Monitoring/OperatingTime/LastReset: Status = Thu Jan 01 1970 01:00:00 GMT+0100 (Central European Standard Time)

9:59:37.897: Event data: (192.168.10.105) Monitoring/OperatingTime/LastClockSynchronization: Status = Thu Jan 01 1970 01:00:00 GMT+0100 (Central European Standard Time)

9:59:54.780: Event data: (192.168.10.105) Device/Trigger/DigitalInput: LogicalState = true

10:0:26.452: Event data: (192.168.10.105) Device/Trigger/DigitalInput: LogicalState = false
10:0:42.036: Sending log

**Comment by AdyRock** [comment]
Could you try the test version that's in the store as  I have updated the library to try and cope with cameras that are not returning the date.

Just add '/test' to the normal app URL in the store to install it.

**Comment by AdyRock** [comment]
Also try changing the ONVIF motion notification to use option to digital input as it looks like your camera is presenting that.

**Comment by jho80** [comment]
Thank you! Not sure if it was only the digital input option or also the test version, but now it works!
