### ISSUE TITLE
Add rtsp support and capture image from stream

### ISSUE THREAD

**Issue by antonhagg** [AdyRock/com.onvif#29]
My camera does not support still images, but support a stream over the rtsp protocoll. Would it be possible to add rtsp support and to capture a still image from the stream?

**Comment by AdyRock** [comment]
Sadly, not possible.
Homey doesn't have the processing power to receive an RTSP stream and convert it.

**Comment by antonhagg** [comment]
Really, is it that heavy? I light be possible to just store the I-frame. At least it is better than nötning. https://stackoverflow.com/questions/54562640/capturing-a-single-image-from-an-rtsp-h-264-video-stream#54562762
And 
https://github.com/jcriger/rtsp-grabber

**Comment by AdyRock** [comment]
Homey has to run multiple apps so is only allowed a small percentage of processor time else it gets shutdown.
Those examples look simple but they are using libraries that hide a lot of code.
