### ISSUE TITLE
NVR - SOAP error

### ISSUE THREAD

**Issue by alexeir1** [AdyRock/com.onvif#30]
Hi I do have a Hikvision NVR. When connecting from Homey I get the error “wrong ONVIF soap response”

Can someone help?
Thanks

**Comment by AdyRock** [comment]
I'm not sure if I missed this or if I answered it via the Forum, so apologies if I have missed it.
Can you enable the full log Information log in the Configure App screen, make the error happen and then send the log from the same screen.
