### ISSUE TITLE
Reolink doorbell 

### ISSUE THREAD

**Issue by robvos** [AdyRock/com.onvif#37]
I have the new Reolink Doorbell.  
Would it be possible to use the signal when someone presses the doorbell button?

Herewith the log I get when the doorbell is pressed. 

19:28:35.552: 
--  Event detected (Deurbel )  --
19:28:35.556: {
  "topic": {
    "_": "tns1:RuleEngine/MyRuleDetector/Visitor",
    "$": {
      "Dialect": "http://www.onvif.org/ver10/tev/topicExpression/ConcreteSet"
    }
  },
  "message": {
    "message": {
      "$": {
        "UtcTime": "2022-11-30T19:28:35.000Z",
        "PropertyOperation": "Changed"
      },
      "source": {
        "simpleItem": {
          "$": {
            "Name": "Source",
            "Value": "000"
          }
        }
      },
      "data": {
        "simpleItem": {
          "$": {
            "Name": "State",
            "Value": true
          }
        }
      }
    }
  }
}

19:28:35.559: Event data: (Deurbel ) RuleEngine/MyRuleDetector/Visitor: State = true
19:28:35.563: Ignoring event type (Deurbel ) RuleEngine/MyRuleDetector/Visitor: State = true
19:28:50.370: 
--  Event detected (Deurbel )  --
19:28:50.379: {
  "topic": {
    "_": "tns1:RuleEngine/MyRuleDetector/Visitor",
    "$": {
      "Dialect": "http://www.onvif.org/ver10/tev/topicExpression/ConcreteSet"
    }
  },
  "message": {
    "message": {
      "$": {
        "UtcTime": "2022-11-30T19:28:50.000Z",
        "PropertyOperation": "Changed"
      },
      "source": {
        "simpleItem": {
          "$": {
            "Name": "Source",
            "Value": "000"
          }
        }
      },
      "data": {
        "simpleItem": {
          "$": {
            "Name": "State",
            "Value": false
          }
        }
      }
    }
  }
}

19:28:50.386: Event data: (Deurbel ) RuleEngine/MyRuleDetector/Visitor: State = false
19:28:50.389: Ignoring event type (Deurbel ) RuleEngine/MyRuleDetector/Visitor: State = false
19:29:24.621:

**Comment by AdyRock** [comment]
It looks promising. I will have a closer look tomorrow.

**Comment by robvos** [comment]
Ok, thanks.
If you need more logs or info, please let me know.

⁣Best regards,
Rob Vosters

BlueMail voor Android downloaden ​

Op 30 nov. 2022 22:17, om 22:17, Adrian Rockall ***@***.***> schreef:

**Comment by AdyRock** [comment]
I have published a test version (https://homey.app/a/com.onvif/test/) that should show the doorbell press as a generic alarm. The capability should appear once it has detected the first press and then you should also get the flow trigger option as well.
Let me know how it goes.

**Comment by robvos** [comment]
I tested this version. 
If I am correct,  after installation,  I should press the doorbell once. 
Should I than get an extra flow card that is triggered by the button press?

Currently I do not have the extra flow card. 

⁣I rebooted the Homey once and also the app.

Op 1 dec. 2022 17:35, om 17:35, Adrian Rockall ***@***.***> schreef:

**Comment by AdyRock** [comment]
That was the theory. When the app got the event it should now recognise it and add the generic_alarm capability. You should see that in the device and, as it's a built in capability, it should have add the flow trigger card. 
Could you send a new log with the event captured again so I can see if it recognised it?

**Comment by robvos** [comment]
Log ID: 2022-12-01T22:11:01.272Z
App version 2.0.17

22:11:1.272: 
--  Event detected (Deurbel )  --
22:11:1.276: {
  "topic": {
    "_": "tns1:RuleEngine/MyRuleDetector/Visitor",
    "$": {
      "Dialect": "http://www.onvif.org/ver10/tev/topicExpression/ConcreteSet"
    }
  },
  "message": {
    "message": {
      "$": {
        "UtcTime": "2022-12-01T22:11:01.000Z",
        "PropertyOperation": "Changed"
      },
      "source": {
        "simpleItem": {
          "$": {
            "Name": "Source",
            "Value": "000"
          }
        }
      },
      "data": {
        "simpleItem": {
          "$": {
            "Name": "State",
            "Value": true
          }
        }
      }
    }
  }
}

22:11:1.279: Event data: (Deurbel ) RuleEngine/MyRuleDetector/Visitor: State = true
22:11:1.284: Ignoring event type (Deurbel ) RuleEngine/MyRuleDetector/Visitor: State = true
22:11:14.634: Sending log
22:11:16.057: Message sent: ***@***.***>
22:11:16.685: 
--  Event detected (Deurbel )  --
22:11:16.692: {
  "topic": {
    "_": "tns1:RuleEngine/MyRuleDetector/Visitor",
    "$": {
      "Dialect": "http://www.onvif.org/ver10/tev/topicExpression/ConcreteSet"
    }
  },
  "message": {
    "message": {
      "$": {
        "UtcTime": "2022-12-01T22:11:16.000Z",
        "PropertyOperation": "Changed"
      },
      "source": {
        "simpleItem": {
          "$": {
            "Name": "Source",
            "Value": "000"
          }
        }
      },
      "data": {
        "simpleItem": {
          "$": {
            "Name": "State",
            "Value": false
          }
        }
      }
    }
  }
}

22:11:16.695: Event data: (Deurbel ) RuleEngine/MyRuleDetector/Visitor: State = false
22:11:16.699: Ignoring event type (Deurbel ) RuleEngine/MyRuleDetector/Visitor: State = false

Op 1 dec. 2022 21:05, om 21:05, Adrian Rockall ***@***.***> schreef:

**Comment by AdyRock** [comment]
OK, I think I see my error so I have published a new test version.

**Comment by robvos** [comment]
This works. 
With the doorbell I see the general alarm. 
A normal reolink cam is not showing the general alarm. 
Also the flow is working. 

Fast implementation. 
Thanks. 

Op 2 dec. 2022 00:08, om 00:08, Adrian Rockall ***@***.***> schreef:

**Comment by AdyRock** [comment]
Great, thanks for the update. It's nice when users let me know when things work 👍
