### ISSUE TITLE
Reolink NVR motion/ add problem

### ISSUE THREAD

**Issue by cyber-93** [AdyRock/com.onvif#40]
Hi
thanks for the app and all the work

first some information about the setup
onvif app latest version also tested with test version
NVR:
model: Reolink RLN8-410
hardware: N3MB01
firmware: V3.2.0.214_22120252

cam 1: Reolink poe video doorbell (channel 0 token 000)
cam 2: camera: RLC-810A (channel 1 token 001)
cam 3: camera: RLC-810A (channel 2 token 002)
cam 4: camera: RLC-810A (channel 3 token 003)
all directly connected to the NVR.

I don’t know if this is related to the motion problem but 

when I add the NVR to your onvif app the channel numbers get setup wrong.
camera 1 gets added as channel 1 and token 000 should be channel 0 and token 000
camera 2 gets added as channel 2 and token 001 should be channel 1 and token 001
etc.

when I don’t change anything.
obviously snapshots don’t work for the correct camera (cam1 shows cam 2, cam2 shows cam3, etc cam 4 shows no image (because there is no cam 5).

now the issue.

when I than trigger motion on camera 1 you’re app shows motion on camera 3 and camera 4.
When motion on cam 2. The app shows motion on cam 2,3 and 4

When I change the channel numbers in the app : channel 1 to 0, channel 2 to 1, etc.
Now the snapshots work like they should.
When I than trigger motion on camera 1 you’re app shows sometimes no motion and sometimes motion on multiple cameras,  2 still triggers channel 2,3 and 4  

I’ve attached some screenshots form the onvif device manager
and some logs from the app, see bottom of the post.

I would also like to request a feature for the app.

To add a tag to the motion detection card 

the tag should than display the kind of motion that is detected 
IsMotion
IsPerson
IsVehicle
IsVisitor
Etc.

![onvif app](https://user-images.githubusercontent.com/120966740/210623395-8791f5cd-4737-41dc-8574-5e977a49463d.png)
![onvif app2](https://user-images.githubusercontent.com/120966740/210623402-a00d3382-6a8c-4daf-bbeb-da0a4bb6f909.png)
[instalation.txt](https://github.com/AdyRock/com.onvif/files/10346627/instalation.txt)
[onvif app.txt](https://github.com/AdyRock/com.onvif/files/10346576/onvif.app.txt)

If you need any more information please ask

greets Luuk 

Edit. 
I just reinstall the app and now motion on cam 1 and cam 2 displays as motion on camera 4
see new log 

[new log.txt](https://github.com/AdyRock/com.onvif/files/10346692/new.log.txt)
onvif device manager stil displays correct tokens etc.

**Comment by AdyRock** [comment]
OK, I think I can see part of the problem. It seems the push events only discriminate via the IP address which is not enough for a multi-channel NVR.
The channel number is set via the device entry + 1 as that is all the information I had from the previous user with such a configuration. Could you set the log to Full Information, clear it and then run the through the Add Device wizard so a discovery is performed (no need to actually add anything). Then could you send the log so I can see if the channel is reported back.

**Comment by cyber-93** [comment]
thanks for the fast reply
here by the new log
can’t seem to capture the full log can only capture about 30 sec 600 lines 
[add log.txt](https://github.com/AdyRock/com.onvif/files/10350786/add.log.txt)

Also send it directly via the app.

**Comment by AdyRock** [comment]
OK, as expected there is nothing to determine the channel except the order in which they appear. The previous user that help me add multi-channel support required the channels to be numbered from 1 to x, hence the app sets the channel to index +1. So I am inclined to leave that bit alone for now as it can be manually fixed.

As far as the events going to the wrong cameras is concerned, which is obviously more serious, I have attempted a fix and published a new test version. Could you try that and let me know if it solves that problem?

**Comment by cyber-93** [comment]
Hi 
don’t worry about the channel numbering, it is easy enough for the user to correct.
I just mention it because it thought it might by related.

Thanks for the software update.
I compledly removed the app and did a clean install.
Change the channel number again, turned pull events on and turned motion detection on.
But the update didn’t fix the problem.
motion triggered on any camera still triggers motion on cam 2, 3 and 4.
Cam 1 triggers 2,3 and 4
Cam 2 triggers 2,3 and 4
Etc

Turned off motion and than turned is back on 
Now cam 1 doesn’t trigger any motion any more 
Cam 2 triggers motion on cam 1,2 and 3

Turn motion off and on again 
cam 1 still doen’t trigger
cam 2 now triggers cam 1,3 and 4

Turned it off and on again now,
cam 1 triggers cam 1,2 and 4
Cam 2 triggers cam 1,3 and 4
And some of the motion triggers stay on 

Also tried turning off pull events but then I get the error, and no motion detection

10:37:39.358: Wrong channel token
10:37:39.369: Push Event unknown Device: 192.168.0.73
10:37:43.419: Push event: <?xml version="1.0" encoding="UTF-8"?>

[log pull event on.txt](https://github.com/AdyRock/com.onvif/files/10359782/log.pull.event.on.txt)

Not Sure what 192.168.0.73 is it doesn’t exist on my network
The NVR: 192.168.0.7
Homey: 192.168.0.5

motion log: 
[motion.txt](https://github.com/AdyRock/com.onvif/files/10359778/motion.txt)
add log check for new camera's
[add log.txt](https://github.com/AdyRock/com.onvif/files/10359821/add.log.txt)

**Comment by AdyRock** [comment]
Ah, I tried to fix push not pull but looks like it is another issue with that. The 192.168.0.73 is the IP address with the channel number appended to identify it. It works on my individual cameras as it should just be a field for a user identifier, but it seems the NVR treats that in a different way.

For the pull events, it appears to be working OK from the logs so there is probably a similar issue with the call to register events.
I will look deeper into all this and get back to you.

**Comment by AdyRock** [comment]
I have published a new test version. Please could you install it and then do the following:
1. Turn off motion detection on all the cameras.
2. Set log level to Errors Only.
3. Restart the app.
4. Send the log.
5. clear the log.
6. Set the log level to Full Information.
7. enable the motion on camera 1 and then disable it.
8. enable the motion on camera 2 and then disable it.
9. enable the motion on camera 3 and then disable it.
10. enable the motion on camera 4 and then disable it.
11. send the log.
12. clear the log.
13. enable the motion on camera 1.
14. trigger motion on camera 1.
15. disable motion on camera 1.
16. enable the motion on camera 1.
17. trigger motion on camera 1.
18. disable motion on camera 1.
19. send the log.

I can't see anything in the ONVIF specifications about multiple channels via an NVR so this is all trial and error.

What NVR / cameras do have?

**Comment by AdyRock** [comment]
Typical, I updated the ONVF library to see if that would help and it seems it has made things worse as now there is an XML error when it tries to enable Motion.

I have published a new test version that logs the request so I can see what is being sent as it is working fine on all my cameras.
Could you install the new version and then repeat steps 1, 5 6, 7 and 11.

What NVR do you have as I might consider buying the same if this doesn't working out.

**Comment by cyber-93** [comment]
send the log

NVR:
model: Reolink RLN8-410
hardware: N3MB01
firmware: V3.2.0.214_22120252

**Comment by AdyRock** [comment]
I have just purchased that NVR so hopefully testing should be easier.

**Comment by cyber-93** [comment]
I didn’t think the problem is this difficult to fix.
I thought it was just an assignment problem of the token

Thanks for the effort/time until now

**Comment by AdyRock** [comment]
No problem. I have been contemplating changing mine for a while as I can now only access it directly because the http interface is only for IE and as that has now been killed off I can't use that. 
I have been through all the ONVIF documents several times and I can't find any reference to multiple channels. I have also searched the Internet and nothing is coming up there. So I'm not sure where to insert the token and there are many options. If I kept trying for you to test it could take weeks.

**Comment by AdyRock** [comment]
My NVR came today but I'm very disappointed as it doesn't work with any of my cameras. My H.View works with 5 different models and although the Reolink can detect some of them it isn't able to connect. So I still can't test the multi-channel bits. I have one Reolink camera at the office so I shall bring that home tomorrow to make sure the NVR isn't faulty. If that works then I shall look into to purchasing another one.

**Comment by AdyRock** [comment]
I have had a reply from Reolink and they confirm an issue with the NVR not reporting the source of the event.
They have provided me with a beta firmware to try which fixes that and it does seem to now report the channel in the event. However, there are a few other new bugs I have found in that firmware so I think it will be a few weeks before it is ready for release.
So, progress but not quite there just yet.

**Comment by cyber-93** [comment]
A oke no worries.
Any progress is progress
I just find it a bit strange that it does seem to work in the Onvif device manager
Every event gives a token number, the kind of event e.g. ismotion, is vehicle, isperson etc And a true or false.
And it seems to be correct.
But I’m probably misunderstanding something.
I’m not in a hurry so I will Wait.

**Comment by AdyRock** [comment]
Has Reolink provided new firmware yet?

Could you also try the new Test version to see if that has any improvement?

**Comment by cyber-93** [comment]
I’ve installed the latest firmware from Reolink and the latest test version of the Onvif app, and did some testing.
the camera’s motion now report to the correct channel and I don’t need to turn on pull event’s anymore. Still need to change the channel number manually but that is easy enough for the user.
Person vehicle visitor detection works also 
thanks for all the work.
I now have found some issues.
1.	Channel 0 (reolink doorbell.) can report in the app: visitor (Vistor), face, animal, vehicle, image to dark and person. Al the options the camera has work.
But when I make a flow with the card The Vistor detected alarm turned on and then send a message to the phone nothing happens. With person detection it works.
Maybe just a typo in the app somewhere (vistor visitor).

2.	And a other none related to the above problem and not really a problem for me. The time of the motion reported by the app lags 2 hours behind. The camera overlay reports the correct time and homey also reports correct time. My location the Netherlands summer time.

**Comment by cyber-93** [comment]
Hi
thanks for the app update and all the work you put in the app
the visitor detected works now.
