### ISSUE TITLE
app randomly stops working

### ISSUE THREAD

**Issue by B3rt** [AdyRock/com.onvif#6]
i noticed that the app completely random stops working.
I cannot reproduce the crash myself, it simply is stoppedi am nog doing anything also no flows running, the app us simply stopped by itself.
I send in a report issue with id 18637e80-e126-4b80-8ff4-8b610d5149b6 before i started the app  again.
I hope you can use the send logs.

**Comment by AdyRock** [comment]
Hi,
Unfortunately the log is not helpful in this instance as this is all I get:

> Unfortunately, your app com.onvif (v0.0.24) has crashed.
> Note: this log has been manually submitted by a user.
> Log ID: 18637e80-e126-4b80-8ff4-8b610d5149b6
> 
> User Message:
> Onvif app randomly crashes and simply stops working.
> 
> 
> 
> ---- stdout ----
> 
> 
> ---- stderr ----

By stops working do you mean it shows a || type symbol in that Apps section?
How many cameras do you have connected?
Are events enabled for all of them?
Are you using Pull or Push events?
Can you send me the log from the Configure app section if it has any messages in it.

Can you try the test version (0.0.33) to see if that is the same:
https://homey.app/en-gb/app/com.onvif/ONVIF-Camera/test/

Could you also check that logging is not switched on all the time.

**Comment by B3rt** [comment]
Yes the || icon was in the APP section.

I have 9 camera added.

No events, just added. There is a flow to make a screenshot when the doorbell is pressed, but this has not been triggered (I log this) to stop the app.

Sure, but there are none there, it seems the app just stopped/paused… randomly, currently it is running again.

**Comment by AdyRock** [comment]
Wow, 9 cameras is a lot. I think maybe the 'online' checks for that many cameras are using too much processor time. An app is only allowed to use 1% of the CPU and if it exceeds that it is paused.
I will issue a new test version that increase the polling interval as more cameras are added to reduce the processor load.

**Comment by AdyRock** [comment]
I have pushed a new test version that should smooth out the processor usage for the camera checks. Could you try that to see if it fixes the issue.

**Comment by B3rt** [comment]
I will try to install it, the current version is stopped again, nothing to see in diagnostic log etc

 

Van: Adrian Rockall <notifications@github.com> 
Verzonden: zondag 24 mei 2020 05:46
Aan: AdyRock/com.onvif <com.onvif@noreply.github.com>
CC: B3rt <github@b3rt.com>; Author <author@noreply.github.com>
Onderwerp: Re: [AdyRock/com.onvif] app randomly stops working (#6)

 

I have pushed a new test version that should smooth out the processor usage for the camera checks. Could you try that to see if it fixes the issue.

**Comment by AdyRock** [comment]
Do you still see this problem?
Hopefully the smoothed load on the CU has worked for you.
