### ISSUE TITLE
Motion Detection from a TAPO (TP-Link) C200

### ISSUE THREAD

**Issue by Daggulb** [AdyRock/com.onvif#69]
Hi, I successfully added the TAPO (TP-Link) C200to my Homey Pro 2023 through the ONVIF app, and it reports no problems in the log (Except for "Snapshots NOT supported ...")
Lates firmware on camera, and everything reports fine in the "settings" page in ONVIF

"ONVIF Notification types" reports MOTION
"ONVIF Motion Notification to use" is set to MOTION (IsMOTION), I've aldo tried MOTIONALARM (State)

Still I'm not able to make motion detection work / not able to make ONVIF detect any motion. Motion detection works fine in the TAPO-app.

Any suggestions on settings i can tweek ?

/Dag

**Comment by AdyRock** [comment]
Can you open the app settings page, select the Diagnostics Log tab, change the Log level to Detailed Information and then trigger motion on the camera. After a few minutes tap on Send Log.

**Comment by Daggulb** [comment]
Thank’s – I’ve just sendt the log

 

/Dag

**Comment by AdyRock** [comment]
I have the log but there is no sign of motion events. Have you got motion enable in the Homey device 
![Screenshot_20231114_135350_Homey.jpg](https://github.com/AdyRock/com.onvif/assets/38184396/14b04e1e-2016-4e3c-bb91-4cc9c3f679e1)

**Comment by Daggulb** [comment]
Thank’s ! Trying back and fort and removing / adding the camera, this must have slipped… I’ve tested now with motion enable and it seems to be working 😊

Thanks again / Dag

**Comment by AdyRock** [comment]
No problem. You are not the first to have been caught by that and I sure you won't be the last. 
I intend to rename the button to make it clear what it does but I haven't thought of a suitable phrase yet.
