### ISSUE TITLE
Problems whit D-link cameras vs. ONVIF

### ISSUE THREAD

**Issue by Hadaui** [AdyRock/com.onvif#79]
Hey. I have a D-link cameras (DCS-8627LH). 

I can se it in the ONVIF app, when I try to connect it to my Homey Pro, but I can connect the camera to Homey?

Can you help my

**Comment by Hadaui** [comment]
Error: Timeout after 30000ms

**Comment by Hadaui** [comment]
I use admin as username, pincode from camera as password, ONVIF service port 554 - what is wrong

**Comment by AdyRock** [comment]
Is that the port that was detected automatically?
Maybe you have to configure a username and password in the camera for an ONVIF connection?

**Comment by Hadaui** [comment]
It’s not detecting any port, but I have tried 443, 554, 80, 8080. It’s not possible to configure username in camera. D-link support told me, that the camera is supporting ONVIF and username is admin, password is pin code printed on camera and port 554. 
![IMG_7547](https://github.com/AdyRock/com.onvif/assets/170537272/e2b146fb-c5d7-4b52-86d0-1219c5125768)
![IMG_7548](https://github.com/AdyRock/com.onvif/assets/170537272/10e2277e-6037-4791-a026-c4156f3d70ff)
![IMG_7549](https://github.com/AdyRock/com.onvif/assets/170537272/9440b633-16a0-4346-99b3-e88ac98b7c5b)

**Comment by Hadaui** [comment]
I had 5 cameras and I had the same problem with all of them. Any tips for how I can get them in Homey?

**Comment by Hadaui** [comment]
UPDATE - Now it's suddenly works 😀 I don't know why, but I think someone has updated the app.
