### ISSUE TITLE
Unable to connect with c425 camera 

### ISSUE THREAD

**Issue by L1poro** [AdyRock/com.onvif#82]
Hi

I am unable to detect the c425 Tapo camera with my Homey Pro (2016-2019). The Onvif app does not find the camera and when adding it manually I receive connection issues. I tried many different ports. Sent you the log separately if you are able to support. BR

**Comment by AdyRock** [comment]
Unfortunately, the log doesn't contain any useful information. 
Could you set the log option to Detailed information and then try to add the camera again. Once you have finished the process, even if nothing is found, then send the log again.

**Comment by L1poro** [comment]
Ok, sent a new log.

**Comment by AdyRock** [comment]
The response for diskstation, is that your camera or do you have an NVR on the network?
If that is your camera then you could try adding 192.168.50.185 on port 5357. If it's not then it appears the camera doesn't support ONVIF or the protocol in not enabled.

**Comment by L1poro** [comment]
Not sure what diskstation is referring to to be honest, it is not my camera.


I don't have an NVR but I do have a NAS which is connected via ethernet to my router and this device is named DiskStation. Can't understand how this is connected to the discovery and connection of the Tapo camera. 


The camera should support ONVIF protocol.


I will try to add another C425 camera tomorrow using my mobile network only to see if it pops up.





---- Den Tue, 02 Jul 2024 18:35:24 +0200 skrev ***@***.*** ----



The response for diskstation, is that your camera or do you have an NVR on the network?
If that is your camera then you could try adding 192.168.50.185 on port 5357. If it's not then it appears the camera doesn't support ONVIF or the protocol in not enabled.

**Comment by AdyRock** [comment]
I can’t see any sign of ONVIF in the Tapo C425 specification online. Does it mention it in the documentation you have?

**Comment by L1poro** [comment]
I read somewhere that it did have support for ONVIF but now I found it hasn't based on the information from TP-Link in Q5 in the below link. It seems I was wrong, sorry for that.

https://community.tp-link.com/en/smart-home/forum/topic/634050
